using System;

namespace CybersecurityBotGUI.Models
{
    /// <summary>
    /// Represents a single cybersecurity task stored in the MySQL database.
    /// Maps directly to a row in the `tasks` table (see schema.sql).
    /// </summary>
    public class TaskItem
    {
        /// <summary>Primary key — auto-generated by MySQL. 0 means "not yet saved".</summary>
        public int Id { get; set; }

        /// <summary>Short title of the task, e.g. "Enable two-factor authentication".</summary>
        public string Title { get; set; } = string.Empty;

        /// <summary>Longer description of what the task involves.</summary>
        public string Description { get; set; } = string.Empty;

        /// <summary>Optional reminder date. Null means no reminder was set.</summary>
        public DateTime? ReminderDate { get; set; }

        /// <summary>True once the user has marked this task as completed.</summary>
        public bool IsCompleted { get; set; }

        /// <summary>When the task was originally created.</summary>
        public DateTime CreatedAt { get; set; } = DateTime.Now;

        /// <summary>Friendly display string for the reminder, used in the GUI.</summary>
        public string ReminderDisplay =>
            ReminderDate.HasValue
                ? "Reminder: " + ReminderDate.Value.ToString("dd MMM yyyy")
                : "No reminder set";

        /// <summary>Friendly status label used in the GUI list.</summary>
        public string StatusDisplay => IsCompleted ? "Completed" : "Pending";
    }
}
